### ISSUE TITLE
Improve error messages when fieldnames or typenames start with int: "Syntax Error: Invalid number, expected digit but got: "W". (1:831)"

### ISSUE THREAD

**Issue by MussadiqKhan** [gatsbyjs/gatsby-source-wordpress-experimental#91] opened 2020-07-25 12:59 UTC
@AbeEstrada   I am working on a client's wordpress website. I am using the latest version of gatsby-source-wordpress-experimental but I am getting the following error when I run gatsby develop. Any help would be appreciated.

`Syntax Error: Invalid number, expected digit but got: "W". (1:831)
> 1 |  query NODE_LIST_QUERY($first:Int!,$after:String,){mediaItems(first:$first,after:$after,where:{parent:null}){nodes{altText ancestors(first:100){nodes{id}}author{node{id}}authorDatabaseId authorId caption wpChildren:children(first:100){nodes{id}}commentCount commentStatus comments(first:100){nodes{id}}contentType{node{id}}databaseId date dateGmt description desiredSlug enclosure guid id lastEditedBy{node{id}}link mediaDetails{file height meta{aperture camera caption copyright createdTimestamp credit focalLength iso keywords orientation shutterSpeed title}sizes{file height mimeType name sourceUrl width}width}mediaItemUrl mediaType mimeType modified modifiedGmt wpParent:parent{node{id __typename}}parentDatabaseId parentId sizes slug sourceUrl srcSet status template{__typename ... on DefaultTemplate{templateName}... on 100WidthTemplate{templateName}... on BlankPageTemplate{templateName}... on ContactTemplate{templateName}... on 
SideNavigationTemplate{templateName}}terms(first:100){nodes{id}}title uri __typename}pageInfo{hasNextPage endCursor}}}    | 
`

**Comment by MussadiqKhan** [comment] 2020-07-25 14:00
`SyntaxError: Syntax Error: Invalid number, expected digit but got: "W". (1:831)
  > 1 |  query NODE_LIST_QUERY($first:Int!  3m,$after:String,){mediaItems(first:$first,after:$a  fter,where:{parent:null}){nodes{altText ancestors(first:100  39m){nodes{id}}author{node{id}}authorDatabaseId authorId caption wpChildren:children(first:  100){nodes{id}}commentCount commentStatus comments(first:100){nodes{id}}contentType{node{id  }}databaseId date dateGmt description desiredSlug enclosure guid id lastEditedBy{node{id}}link mediaDetails{file hei  ght meta{aperture camera caption copyright createdTimestamp credit focalLength iso keywords orientation shutterSpeed   title}sizes{file height mimeType name sourceUrl width}width}mediaItemUrl mediaType mimeType modified modifiedGmt wp  Parent:parent{node{id __typename}}parentDatabaseId parentId sizes slug sourceUrl srcSet status template{__  typename ... on DefaultTemplate{templateName}... on 100WidthTemplate  9m{templateName}... on BlankPageTemplate{templateName}... on ContactTemplate  {templateName}... on SideNavigationTemplate{templateName}}terms(first:100){n  odes{id}}title uri __typename}pageInfo{hasNextPage endCursor}}}
      | 
                                                                                                          
                                                                                                          
                                                                                                          
                                                                                                          
                                                                                                          
                                                                                                          
                          ^

  - parser-graphql.js:1 n
    [sellerlift-wordpressgatsby]/[prettier]/parser-graphql.js:1:346

  - parser-graphql.js:1 Object.parse
    [sellerlift-wordpressgatsby]/[prettier]/parser-graphql.js:1:54924

  - index.js:11370 Object.parse
    [sellerlift-wordpressgatsby]/[prettier]/index.js:11370:19

  - index.js:14784 coreFormat
    [sellerlift-wordpressgatsby]/[prettier]/index.js:14784:25

  - index.js:15019 format
    [sellerlift-wordpressgatsby]/[prettier]/index.js:15019:75

  - index.js:15035 formatWithCursor
    [sellerlift-wordpressgatsby]/[prettier]/index.js:15035:12

  - index.js:51620 
    [sellerlift-wordpressgatsby]/[prettier]/index.js:51620:12

  - index.js:51640 Object.format
    [sellerlift-wordpressgatsby]/[prettier]/index.js:51640:12

  - write-queries-to-disk.js:47 writeQueriesToDisk
    [sellerlift-wordpressgatsby]/[gatsby-source-wordpress-experimental]/steps/ingest-remote-schema/write-queries-to-di    sk.js:47:96

  - run-steps.js:23 async runSteps
    [sellerlift-wordpressgatsby]/[gatsby-source-wordpress-experimental]/utils/run-steps.js:23:7

  - index.js:36 async ingestRemoteSchema
    [sellerlift-wordpressgatsby]/[gatsby-source-wordpress-experimental]/steps/ingest-remote-schema/index.js:36:5      

  - run-steps.js:23 async runSteps
    [sellerlift-wordpressgatsby]/[gatsby-source-wordpress-experimental]/utils/run-steps.js:23:7



 ERROR 

 gatsby-source-wordpress 

        Encountered a critical error when running the undefined.writeQueriesToDisk build step.
        See above for more information.`

**Comment by TylerBarnes** [comment] 2020-07-26 03:28
Hi @MussadiqKhan , it's hard to tell what could be causing this from your description. It's odd because somehow there seems to be a random `100` int added to the middle of the query 🤔 
If you're able to share a reproduction repo I can get this fixed for you.

Thanks!

**Comment by MussadiqKhan** [comment] 2020-07-26 07:06
Here's the starter repo I am using. I have just updated the site url in gatsby config.

Repo: https://github.com/MussadiqKhan/sellerlift-wordpressgatsby

**Comment by TylerBarnes** [comment] 2020-07-27 16:20
Hi @MussadiqKhan , I discussed this with @jasonbahl and the issue here is that GraphQL typenames and field names cannot start with numbers (as per the GraphQL spec). See this issue for more information https://github.com/wp-graphql/wp-graphql/issues/1346#issuecomment-650270026

So in this case the problem is that you have a template called `100WidthTemplate` which is invalid in GraphQL. In the linked issue, there are some proposed solutions around auto-excluding these types and providing a helpful debug message. 

This will be fixed upstream in WPGQL, but for now you can rename your 100WidthTemplate and your site should build. If you do this and your build still fails, feel free to re-open this issue or continue commenting here.

Thanks again!

**Comment by TylerBarnes** [comment] 2020-07-28 01:05
Actually, I think it would also be good to fail the build if a typename or fieldname start with an integer so I'll reopen this as a ticket for improved error messaging here.

**Comment by TylerBarnes** [comment] 2021-01-20 18:43
This has been fixed in WPGraphQL so I'm closing this :)

**Closed by TylerBarnes** 2021-01-20 18:43 UTC
Labels: Feat: Improve error messages, todo after v4 release
