### ISSUE TITLE
Aborts connection to wordpress with non-sensical error

### ISSUE THREAD

**Issue by AndrewTraub** [gatsbyjs/gatsby-source-wordpress-experimental#107] opened 2020-07-31 19:45 UTC
I've tried fetching data from both my website and a local installation.
I've verified that WPGraphQL and QPGatsby are installed and working.
With a starter project and only the experimental plugin added, I get the following when trying to run gatsby develop:

success open and validate gatsby-configs - 0.054s
success load plugins - 1.879s
success onPreInit - 0.015s
success initialize cache - 0.025s
success copy gatsby files - 0.123s
success onPreBootstrap - 0.016s
⠀
info  gatsby-source-wordpress

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.175s
success  gatsby-source-wordpress  Category - 2.972s - fetched 7
success  gatsby-source-wordpress  Menu - 8.745s - fetched 2
success  gatsby-source-wordpress  Post - 15.282s - fetched 50
success  gatsby-source-wordpress  Taxonomy - 16.528s - fetched 3

 ERROR

 gatsby-source-wordpress  Unable to connect to WPGraphQL.

Received HTML as a response. Are you sure http://site.local/graphql is the correct URL?

If that URL redirects to the correct URL via WordPress in the browser, or you've entered the wrong URL in settings, you might receive this error.
Visit that URL in your browser, and if it looks good, copy/paste it from your URL bar to your config.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

not finished source and transform nodes - 21.012s
not finished  gatsby-source-wordpress  fetching nodes - 20.934s - 162 total
not finished  gatsby-source-wordpress  Comment - 20.934s
not finished  gatsby-source-wordpress  ContentType - 20.938s
not finished  gatsby-source-wordpress  MenuItem - 20.938s
not finished  gatsby-source-wordpress  Page - 20.925s
not finished  gatsby-source-wordpress  Tag - 20.911s - fetched 100
not finished  gatsby-source-wordpress  User - 20.889s

Any help would be appreciated

**Comment by TylerBarnes** [comment] 2020-08-02 00:55
Hi @AndrewTraub , have you tried following the recommendation in the error?
This is usually caused by
- WPGraphQL not being activated
- Your url is https but you entered http (or vice versa)
- Your url starts with www

If you visit http://site.local/graphql do you see a JSON response like this?
```json
{
  "errors": [
    {
      "message": "GraphQL Request must include at least one of those two parameters: \"query\" or \"queryId\"",
      "extensions": {
        "category": "request"
      }
    }
  ]
}
```

**Comment by AndrewTraub** [comment] 2020-08-03 17:02
Yes, as I mentioned, it appears to connect and run quite a bit (saying many times "fetching nodes - 7 total" and then "success ... UrserRole - 19.101s - fetched 0" and "success ... Taxonomy - 20.272s - fetched 3" and then throws the error.

I have connected to the site using Postman and successfully made a query with Postman to WPGraphQL, so I don't think it's my setup.

After the error, I am also getting this:
not finished source and transform nodes - 24.074s
not finished  gatsby-source-wordpress  fetching nodes - 24.024s - 213 total
not finished  gatsby-source-wordpress  Comment - 24.026s
not finished  gatsby-source-wordpress  ContentType - 24.029s
not finished  gatsby-source-wordpress  MenuItem - 24.030s
not finished  gatsby-source-wordpress  Page - 24.021s
not finished  gatsby-source-wordpress  Post - 24.009s - fetched 100
not finished  gatsby-source-wordpress  Tag - 24.004s - fetched 100
not finished  gatsby-source-wordpress  User - 23.972s

which I would not expect if it were unable to connect at all.

**Comment by TylerBarnes** [comment] 2020-08-04 15:21
Ah, I see that now, it's a bit hard to read your logs when they're unformatted. Heads up, if you add 3 backticks above and below your output it'll put it in a formatted box like this 👍 
```
not finished source and transform nodes - 24.074s
not finished gatsby-source-wordpress fetching nodes - 24.024s - 213 total
```

Can you share your GraphQL endpoint with me and/or a reproduction repo of this issue? If you want to keep your endpoint private my email is tyler@gatsbyjs.com

Thanks Andrew!

**Comment by AndrewTraub** [comment] 2020-08-04 17:15
I sent you an email with the public facing WPGraphQL link.

**Comment by MussadiqKhan** [comment] 2020-08-05 11:36
Hey @TylerBarnes ,

I am also facing the same issue. Would you mind taking a look at my repo? Should I email you the details?

**Comment by TylerBarnes** [comment] 2020-08-05 21:46
@MussadiqKhan that would be helpful! Thank you :)

**Comment by TylerBarnes** [comment] 2020-08-05 23:49
Hi @AndrewTraub I had another look at your site and it appears that after some number of requests your server returns html as a response. When I render this html in a browser it appears to be a regular page from your WP instance. It seems like something is randomly filtering requests and returning html based on something. This may be as a result of Wordfence intercepting requests or something else. I haven't seen this before 🤔 @jasonbahl any ideas?

@MussadiqKhan do you also have Wordfence installed?

**Comment by TylerBarnes** [comment] 2020-08-06 00:11
I believe this is a problem with some filters for specific posts in a WordPress plugin or theme.

@MussadiqKhan I just used your endpoint to debug and I see the following being returned with the GraphQL response:

<img width="1036" alt="Screen Shot 2020-08-05 at 5 08 57 PM" src="https://user-images.githubusercontent.com/14190743/89476045-85259b80-d73e-11ea-9382-fe2583b3be36.png">

I'm not sure if this is something that can be fixed in WPGraphQL or not 🤔 I believe we need to load up posts/pages using all the regular filters they have so that other WP filters work correctly, but it seems there are some here that are outputting other data.

**Comment by TylerBarnes** [comment] 2020-08-06 00:12
@jasonbahl might have advice on a workaround but in the meantime I'm modifying the error message here and adding a debug option to help with debugging.

**Comment by TylerBarnes** [comment] 2020-08-06 00:29
@MussadiqKhan FYI the page that's causing the issue has an id of 4031 and the filter is on the post content.

**Comment by TylerBarnes** [comment] 2020-08-06 00:45
@AndrewTraub it appears one of your pages is redirecting to another page any time that page is accessed in WP. It seems like there's something wrong with the method of redirection here as the redirect seems to be happening when the page is accessed and it should instead happen when the page is visited in a browser.

**Comment by TylerBarnes** [comment] 2020-08-06 02:01
If you upgrade to `gatsby-source-wordpress-experimental@1.2.6` you'll both now see more helpful error messages.

@AndrewTraub you'll see an error about the GraphQL request being redirected.
@MussadiqKhan you'll see an error about a PHP filter adding additional output to the GraphQL request.

In both cases I've added some info about how to proceed with debugging the issue. This isn't a bug with this plugin so I'm closing this issue but please feel free to follow up here or join the [WPGraphQL slack](https://wp-graphql.slack.com/join/shared_invite/zt-3vloo60z-PpJV2PFIwEathWDOxCTTLA#/) for additional help.

Thanks for raising this issue @AndrewTraub and @MussadiqKhan !

**Closed by TylerBarnes** 2020-08-06 02:01 UTC
Labels: upstream

**Comment by MussadiqKhan** [comment] 2020-08-20 12:11
Hey,

Is it possible to somehow skip or ignore that particular page/post?

**Comment by TylerBarnes** [comment] 2020-08-24 16:12
@MussadiqKhan there's no way to programatically determine on the Gatsby side which nodes are problematic. Nodes are fetched in lists using pagination. So for example for Page nodes, the first 100 pages are fetched, then the response contains an indicator of wether there is a second page of 100 or not (and how to find it). When fetching 100 pages, 1 page in the list of 100 fails the entire request which makes it impossible to determine which page it was and also impossible to continue paginating since there's no response and that's needed to get the next page of nodes.

**Comment by MussadiqKhan** [comment] 2020-08-24 18:53
@TylerBarnes How did you find out which page was causing an issue? I made a copy of my site, deleted the page you pointed out, ran everything and still got same error.

Endpoint:  `https://www.staging1.sellerlift.com/graphql`,

**Comment by TylerBarnes** [comment] 2020-08-24 23:28
@MussadiqKhan , to debug you can use the following options:

```js
module.exports = {
	plugins: [
		{
			resolve: `gatsby-plugin-wordpress`,
			options: {
				url: `https://www.staging1.sellerlift.com/graphql`,
				debug: {
					graphql: {
						showQueryVarsOnError: true,
						copyQueryOnError: true,
					},
				},
				schema: {
					perPage: 1,
				},
			},
		},
	],
}
```

This will fetch each type 1 node at a time. When the request fails it will show the query variables in the terminal output and copy the query that failed to your clipboard.
Use a GraphQL client app like GraphiQL or GraphQL playground to make that query with those query variables.
You'll find that some of your fields cause the request to never complete or fail. You'll have to remove fields from the query until it works to identify which fields are problematic. In this case it's the `content` field. If you go through those steps you should be able to query for the database ID of the problematic node to identify it and then find it in WP.

Let me know if any of that doesn't make sense or if you get stuck on it.
Thanks again!

**Comment by MussadiqKhan** [comment] 2020-08-26 14:01
Hey,

I did as per your instructions. Here is what I got: gatsby-source-wordpress  GraphQL vars: {"first":1,"url":"https://www.staging1.sellerlift.com/graphql","after":"YXJyYXljb25uZWN0aW9uOjI5MjM="}

How to debug it further. Graphql won't work on my localhost since build failed. Do I need to install some Graphql plugin on wordpress to run queries and debug it?

**Comment by TylerBarnes** [comment] 2020-08-28 18:32
@MussadiqKhan you can download Graphiql or GraphQL Playground and point those at your WordPress /graphql url.
When the query fails it will copy it to your clipboard, paste it into your chosen GraphQL client, then copy the GraphQL variables from the terminal output and also paste those into your GraphQL client. Then you should be able to identify which posts are causing the issue.
If you're able to give code access to @jasonbahl we might be able to determine if there's a way to account for this situation on the WPGraphQL side. Until now we haven't been able to access a site that has this issue. If you're willing to share your WP instance/code that would be helpful. 
Thanks @MussadiqKhan !

**Comment by MussadiqKhan** [comment] 2020-08-28 19:42
Hey @TylerBarnes,

Thanks. Can I have the email address for Jason? I can send my wordpress admin login details? Will it work?

Thanks

**Comment by MussadiqKhan** [comment] 2020-08-31 12:06
Hey @TylerBarnes,

For the time being I removed pages from wordpress and tried fetching data but now I get another error.

EPERM: operation not permitted, lstat 'C:\Users\musad\OneDrive\Desktop\Fiverr Projects\sellerlift-wordpressgatsby\.cache\caches\gatsby-source-wordpress-experimental\tmp-752478c5df7927eeebc6d6af532c8a88.png'

Please let me know what is it about.

Thanks

**Comment by ddiiorio** [comment] 2020-09-03 19:01
@MussadiqKhan @TylerBarnes 

I have been getting the same error on every production build, ` EPERM: operation not permitted, lstat 'C:\.......`

**Comment by TylerBarnes** [comment] 2020-09-15 19:52
@MussadiqKhan https://www.google.com/search?hl=en&q=EPERM%3A%20operation%20not%20permitted%2C%20lstat
