### ISSUE TITLE
Error query NODE_LIST_QUERY and request failed with status code 503

### ISSUE THREAD

**Issue by MobyDigg** [gatsbyjs/gatsby-source-wordpress-experimental#264] opened 2020-11-02 17:36 UTC
Hi all,

first of all, thank you for this great plugin! I am really loving it so far. :-) But now I ran into some problems, hopefully you can help… This error happens on several of my websites. It occurs in combination with #265 

I have migrated multiple sites to the newer gatsby-source-wordpress-experimental plugin and now get the following errors while building. 

- I tested the build on **Netlify** and **GatsbyCloud** – both without luck. 
- Worked before with regular gatsby-source-wordpress plugin, which worked fine.

**App setup:**

- gatsby-source-wordpress-experimental v. ^2.0.4
- gatsby-plugin-netlify-cache v. ^1.2.0 - idk if that matters.
- I use the following gatsby-source-wordpress-experimental options:

```
{
      resolve: 'gatsby-source-wordpress-experimental',
      options: {
        url: config.graphQLUrl,
        verbose: true,
        schema: {
          queryDepth: 10,
          perPage: 10,
          typePrefix: `Wp`,
          timeout: 50000
        },
        develop: {
          nodeUpdateInterval: 600000,
          hardCacheMediaFiles: false
        },
        production: {
          hardCacheMediaFiles: false
        },
        debug: {
          graphql: {
            showQueryOnError: true,
            showQueryVarsOnError: true,
            copyQueryOnError: true,
            panicOnError: false,
            onlyReportCriticalErrors: true
          }
        },
        excludeFieldNames: [`blocksJSON`, `saveContent`, `user`, `Tag`],
        type: {
          CoreParagraphBlockAttributes: {
            exclude: true
          },
          CoreParagraphBlockAttributesV2: {
            exclude: true
          },
          CorePullquoteBlockAttributes: {
            exclude: true
          }
        }
      }
    },
```

**In gatsby-node.js:**

```
const { resolve } = require(`path`);

exports.createPages = async ({ actions, graphql }) => {
  const {
    data: {
      allWpContentNode: { nodes: contentNodes }
    }
  } = await graphql(/* GraphQL */ `
    query ALL_CONTENT_NODES {
      allWpContentNode(
        sort: { fields: modifiedGmt, order: DESC }
        filter: { nodeType: { nin: ["MediaItem", "Employee"] } }
      ) {
        nodes {
          nodeType
          uri
          id
          status
          slug
          ... on WpCompetence {
            language {
              slug
            }
          }
          ... on WpPage {
            language {
              slug
            }
          }
          ... on WpPost {
            language {
              slug
            }
          }
          ... on WpProject {
            language {
              slug
            }
          }
          ... on WpJob {
            language {
              slug
            }
          }
        }
      }
    }
  `);

  const contentTypeTemplateDirectory = `./src/templates/`;

  await Promise.all(
    contentNodes.map(async (node, i) => {
      const { uri, id, slug, language } = node;
      const templatePath = `${contentTypeTemplateDirectory}Page.jsx`;

      // set home page path
      let edgePath = uri;
      if (slug === "home" && language.slug !== "de")
        edgePath = `/${language.slug}/`;

      await actions.createPage({
        component: resolve(templatePath),
        path: edgePath,
        context: {
          id,
          slug,
          lang: language.slug,
          next: (contentNodes[i + 1] || {}).id,
          prev: (contentNodes[i - 1] || {}).id
        }
      });
    })
  );
};
```

**Build command in package.json:**

```
"build": "GATSBY_CONCURRENT_DOWNLOAD=2 gatsby build; netlify-lambda build functions",
```

**WordPress backend setup:**

- WPGatsby v. 0.5.4
- WPGraphQL v. 0.14.0
- WPGraphQL for Advanced Custom Fields v. 0.3.5
- WP GraphQL Polylang v. 0.5.0

**I tried:**

- **Clearing cache** and re-building doesn't work. 
- Playing with **schema.queryDepth** and **schema.perPage** - without luck.
- Tuning down concurrent downloads with **GATSBY_CONCURRENT_DOWNLOAD=2** flag in the package build command - doesn't help.

### Errors I get:

```
6:16:12 PM: success  gatsby-source-wordpress  ingest WPGraphQL schema - 6.392s
6:16:12 PM: success createSchemaCustomization - 12.873s
6:16:12 PM: info  gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"https://eham-admin.mobydigg.de/graphql","after":null}
6:16:12 PM: error  gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) { ... }
```

```
6:16:12 PM: info  gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"https://eham-admin.mobydigg.de/graphql","after":null}
6:16:12 PM: error  gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) { ... }
```

```
6:16:12 PM: info  gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"https://eham-admin.mobydigg.de/graphql","after":null}
6:16:12 PM: error  gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) { ... }
```

```
6:16:12 PM: error  gatsby-source-wordpress  Request failed with status code 503
6:16:12 PM: Error occured while fetching nodes of the "ContentType" type.
6:16:12 PM: GraphQL request to https://eham-admin.mobydigg.de/graphql failed.
6:16:12 PM: Please ensure the following statements are true
6:16:12 PM:   - your WordPress URL is correct in gatsby-config.js
6:16:12 PM:   - your server is responding to requests
6:16:12 PM:   - WPGraphQL and WPGatsby are installed in your WordPress backend
```

-> I checked all those hints, all of those are working.

…then this happens:

```
6:16:12 PM: not finished source and transform nodes - 0.723s
6:16:12 PM: not finished  gatsby-source-wordpress  fetch root fields - 0.668s
6:16:12 PM: not finished  gatsby-source-wordpress  fetching nodes - 0.666s - 0 total
6:16:12 PM: not finished  gatsby-source-wordpress  Category - 0.664s
6:16:12 PM: not finished  gatsby-source-wordpress  Comment - 0.663s
6:16:12 PM: not finished  gatsby-source-wordpress  Competence - 0.662s
6:16:12 PM: not finished  gatsby-source-wordpress  ContentType - 0.662s
6:16:12 PM: not finished  gatsby-source-wordpress  Department - 0.662s
```

The site build finishes on Netlify but shows the typical "Page Not Found" page. On GatsbyCloud the build doesn't finish at all. On GatsbyCloud I get this error message (which varies from time to time…):

```Failed Generating image thumbnails 599.65s```
```Failed Building static HTML for pages 8.14s```
```Failed Building static HTML failed for path "/en/career/helferin-oberflache-lack-en/"```

Thank you for looking into it. I appreciate it.

**Comment by TylerBarnes** [comment] 2020-11-12 21:55
Hi @MobyDigg , thanks for opening this issue!
This is a problem of your server being overwhelmed by requests. 
The current solutions are 
- Try raising the memory limit of your WP instance
- Try lowering `options.schema.perPage` from it's default of 100
- Trylowering `process.env.GATSBY_CONCURRENT_DOWNLOAD` from its default of 200

Closing this as a duplicate of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/85

Short term we will be improving error messages related to this. Long term we will make this plugin more efficient and additionally have it auto-reconfigure itself when running into these problems.

**Closed by TylerBarnes** 2020-11-12 21:55 UTC
