### ISSUE TITLE
When adding or deleting a media item that has been assigned to a field preview-build erorr

### ISSUE THREAD

**Issue by garryburch** [gatsbyjs/gatsby-source-wordpress-experimental#384] opened 2020-12-19 12:56 UTC
When deleting media items or adding a different media item to a field during dev/preview

```
6:23:03 PM: ⠀
6:23:03 PM: info  gatsby-source-wordpress  deleted mediaItem continuous-analytics (#28464)
6:23:03 PM: ⠀
6:23:03 PM: ⠀
6:23:03 PM: info  gatsby-source-wordpress  deleted mediaItem fast-analytics (#28466)
6:23:03 PM: ⠀
6:23:03 PM: ⠀
6:23:03 PM: info  gatsby-source-wordpress  deleted mediaItem comprehensive-analytics (#28462)
6:23:03 PM: ⠀
6:23:03 PM: ⠀
6:23:03 PM: info  gatsby-source-wordpress  update page Free Trial Landing Page (#22212)
6:23:03 PM: ⠀
6:23:03 PM: ⠀
6:23:04 PM: ⠀
6:23:04 PM: info  gatsby-source-wordpress  update page KPI Diagnosis Landing Page (#21071)
6:23:04 PM: ⠀
6:23:04 PM: ⠀
6:23:04 PM: ⠀
6:23:04 PM: info  gatsby-source-wordpress  update page Request A Demo (#1024)
6:23:04 PM: ⠀
6:23:04 PM: ⠀
6:23:32 PM: error Error: url passed to create-remote-file-node is either missing or not a proper web uri: /static/cb56d536ef0694c2e829c2889b3b2924/continuous-analytics-v2.svg
6:23:32 PM:     at module.exports (/opt/build/repo/node_modules/gatsby-source-wordpress-experimental/src/steps/source-nodes/create-nodes/create-remote-file-node/index.js:427:7)
6:23:32 PM:     at remoteFileNode (/opt/build/repo/node_modules/gatsby-source-wordpress-experimental/src/steps/source-nodes/create-nodes/create-remote-media-item-node.js:268:26)
6:23:32 PM:     at RetryOperation.runAttempt [as _fn] (/opt/build/repo/node_modules/async-retry/lib/index.js:41:15)
6:23:32 PM:     at Timeout._onTimeout (/opt/build/repo/node_modules/retry/lib/retry_operation.js:81:10)
6:23:32 PM:     at ontimeout (timers.js:436:11)
6:23:32 PM:     at tryOnTimeout (timers.js:300:5)
6:23:32 PM:     at listOnTimeout (timers.js:263:5)
6:23:32 PM:     at Timer.processTimers (timers.js:223:10)
6:23:32 PM: error  gatsby-source-wordpress 
6:23:32 PM: 	Encountered a critical error when running the sourceNodes.sourceNodes build step.
6:23:32 PM: 	See above for more information.
6:23:32 PM: not finished source and transform nodes - 30.365s
6:23:32 PM: not finished  gatsby-source-wordpress  pull updates since last build - 30.276s
6:23:32 PM: not finished Downloading remote files - 27.315s
6:23:32 PM: error Command failed with exit code 1.
6:23:32 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
6:23:32 PM: 
6:23:32 PM: ────────────────────────────────────────────────────────────────
6:23:32 PM:   "build.command" failed                                        
6:23:32 PM: ────────────────────────────────────────────────────────────────
```

```
  System:
    OS: Linux 5.4 KDE neon 5.20
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.22.1 - ~/.nvm/versions/node/v10.22.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v10.22.1/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.1/bin/npm
  Browsers:
    Firefox: 84.0
  npmPackages:
    gatsby: ^2.24.72 => 2.28.2
    gatsby-background-image: ^0.8.15 => 0.8.19
    gatsby-cli: ^2.12.65 => 2.15.1
    gatsby-image: ^2.4.13 => 2.7.0
    gatsby-plugin-canonical-urls: ^2.3.6 => 2.6.0
    gatsby-plugin-csp: ^1.1.3 => 1.1.3
    gatsby-plugin-feed: ^2.5.11 => 2.9.0
    gatsby-plugin-google-tagmanager: ^2.1.13 => 2.7.0
    gatsby-plugin-manifest: ^2.2.21 => 2.8.0
    gatsby-plugin-netlify: ^2.3.13 => 2.7.0
    gatsby-plugin-offline: ^3.2.21 => 3.6.0
    gatsby-plugin-postcss: ^2.1.11 => 2.3.13
    gatsby-plugin-react-helmet: ^3.1.11 => 3.6.0
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.18 => 2.7.0
    gatsby-plugin-sharp: ^2.2.32 => 2.10.1
    gatsby-plugin-sitemap: ^2.2.17 => 2.8.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.13 => 1.1.18
    gatsby-source-filesystem: ^2.1.31 => 2.7.0
    gatsby-source-wordpress-experimental: ^5.0.2 => 5.0.2
    gatsby-transformer-sharp: ^2.2.21 => 2.8.0
  npmGlobalPackages:
    gatsby-cli: 2.16.1
```

WP Gatsby
Version 0.8.0
	
WP GraphQL
Version 1.0.3

**Comment by gustavo-a** [comment] 2021-01-03 21:36
Same error, downgraded WP GraphQL to 1.0.1 and it worked just fine.

**Comment by garryburch** [comment] 2021-01-05 17:26
> Same error, downgraded WP GraphQL to 1.0.1 and it worked just fine.

This did not resolve the issue - Here is another opened ticket that matches my issue https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/384

**Comment by acao** [comment] 2021-01-06 19:31
is anyone able to provide a repo that reproduces this bug? it looks like we may be trying to reprocess files as if they are remote based on some edge case

**Comment by garryburch** [comment] 2021-01-06 20:05
> is anyone able to provide a repo that reproduces this bug? it looks like we may be trying to reprocess files as if they are remote based on some edge case

I can share one of the 3 sites of ours that is doing this.

Shall I add your user to a copy of one of these?

**Comment by TylerBarnes** [comment] 2021-01-07 18:40
A fix has been published in gatsby-source-wordpress-experimental@6.1.0! If you're still having problems, feel free to comment here or re-open this issue.
Thanks!

**Closed by TylerBarnes** 2021-01-07 18:40 UTC
Labels: needs reproduction, type: question or discussion
