### ISSUE TITLE
Local by FlyWheel and No Schema Available

### ISSUE THREAD

**Issue by kalebheitzman** [gatsbyjs/gatsby-source-wordpress-experimental#108] opened 2020-08-03 20:46 UTC
I'm running Local by FlyWheel and there is no schema available in the explorer under /___graphql.

The only error I'm getting in the console is:

```
Uncaught (in promise) TypeError: Cannot read property 'enableRefresh' of undefined
    at app.js?79533e86a2470d8aa270:13
```

Using the 2 included plugins in the starter instead of the git versions (and upgraded wp-gatsby under plugin admin).

I get a few dev warnings as well:

```
warn Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property
```

**Comment by kalebheitzman** [comment] 2020-08-03 21:29
An update: I'm able to access the schema in GraphQL playground but the default http://localhost:8000/___graphql schema is not working.

**Comment by kalebheitzman** [comment] 2020-08-03 21:40
Last bit of info that might be useful. I added this to my package.json file. Still no schema coming through but it does work in the stand alone GraphQL Playground App.

```
    "develop": "GATSBY_GRAPHQL_IDE=playground gatsby develop",
```

**Comment by lqze** [comment] 2020-08-04 02:09
Adding to this, noticed this exact same issue as well but did not look further into it.

I get the same ```
warn Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property
```

**Comment by TylerBarnes** [comment] 2020-08-06 23:43
The `warn Warning: Empty string transition configs (e.g., { on: { '': ... }}) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property` warning was fixed in a recent version of Gatsby core and is unrelated to this issue.

I'm able to reproduce the schema issue locally. I'm debugging now and I'll keep yall updated on what I find. 

Thanks for opening this issue!

**Comment by TylerBarnes** [comment] 2020-08-07 00:12
So this is either a Gatsby core bug or a GraphQL playground bug. Essentially what happens is Gatsby generates a filter input for the WpContentNode type so that you can filter for nodes that have a specific user that last edited that node. That's great and works well. For example this works:

```
{
  allWpContentNode(filter: {lastEditedBy: {node:{id: {eq: "dXNlcjox"}}}}) {
    nodes {
      ... on WpPage {
        lastEditedBy {
          node {
            id
          }
        }
      }
    }
  }
}
```

The problem here is that the input type `WpContentNodeToEditLastConnectionEdgeFilterInput` has no fields. GraphQL playground builds the SDL for the schema and that produces:

```graphql
input WpContentNodeToEditLastConnectionEdgeFilterInput {

}
```

Now since there are no fields, GraphQL playground errors because it's GraphQL parser doesn't like this. I think this is actually invalid SDL so the error is valid but I have no idea wether it's Gatsby, GraphQL Playground, or the GraphQL parser that gql playground is using which is causing this error.

In any case this isn't a bug with this plugin as these types are automatically generated by Gatsby core when nodes are created. I'm going to close this but I would encourage you to open this issue in the Gatsby core repo and reference this thread.

Thanks again!

**Closed by TylerBarnes** 2020-08-07 00:12 UTC
Labels: bug

**Comment by lqze** [comment] 2020-08-08 08:29
> I'm running Local by FlyWheel and there is no schema available in the explorer under /___graphql.
> 
> The only error I'm getting in the console is:
> 
> ```
> Uncaught (in promise) TypeError: Cannot read property 'enableRefresh' of undefined
>     at app.js?79533e86a2470d8aa270:13
> ```
> 
> Using the 2 included plugins in the starter instead of the git versions (and upgraded wp-gatsby under plugin admin).
> 
> I get a few dev warnings as well:
> 
> ```
> warn Warning: Empty string transition configs (e.g., `{ on: { '': ... }}`) for transient transitions are deprecated. Specify the transition in the `{ always: ... }` property
> ```

I know this Issue is closed, however updating my Gatsby version to latest fixed this for me.

**Comment by TylerBarnes** [comment] 2020-08-10 18:35
That's great to hear, thanks for the update @lqze !

**Comment by kalebheitzman** [comment] 2020-08-11 16:31
So the starter listed in the tutorial had Gatsby set to a an older version of Gatsby. I see it's updated over in the repo. I updated mine to the latest version of Gatsby and everything is working fine. Is it best practice to set a specific version of Gatsby vs specifying a minimum version of Gatsby? Thanks for all the helpful info!

**Comment by TylerBarnes** [comment] 2020-08-12 18:24
@kalebheitzman minimum version is definitely better practise. I think it was an oversight on my part where I accidentally set a specific version but it should be fixed now 👍
