### ISSUE TITLE
Issue with image links with special character

### ISSUE THREAD

**Issue by patrikarvidsson** [gatsbyjs/gatsby-source-wordpress-experimental#184] opened 2020-09-28 17:21 UTC
I'm having issues downloading some images from a fairly long-running (Swedish) Wordpress site.

We are using `WP Offload Media` and uploading images to AWS/DO buckets, where a _working link_ is generated as `file url`. Although this plugin seems to fetch another URL instead. 

**Original filename**
nyttigt-mellanmål_proteinkakor.jpg

**WP Offload Media**
nyttigt-mellanma%CC%8Al_proteinkakor.jpg

**Source plugin**
nyttigt-mellanma%25CC%258Al_proteinkakor.jpg

There are quite a few occurrences with `åäö` and it seems that something is up with the encoding translation. I'm not sure what we can do about it (I haven't encountered a lot of this stuff before), but maybe some light can be shed on the issue here.

EDIT:

As pointed out by @chip2n, it seems that decoding `nyttigt-mellanma%25CC%258Al_proteinkakor.jpg` twice results in `nyttigt-mellanmål_proteinkakor.jpg`. Could it be that something happened when fixing #7 ?

**Comment by TylerBarnes** [comment] 2020-09-28 17:39
@patrikarvidsson , it could be indeed. Perhaps WPGraphQL is handling this in later versions. Are you able to share your /graphql api url so I can easily reproduce this? Or is it enough for me to upload an image with `nyttigt-mellanmål_proteinkakor.jpg` as a filename?

I'll get this fixed asap and add a test for this to prevent future regressions.

Thanks!

**Comment by patrikarvidsson** [comment] 2020-09-29 05:25
@TylerBarnes No problems. I'll send you a mail at your tyler@gatsbyjs.com. There are more than this occurrence so you might benefit from the actual api for testing.

**Comment by TylerBarnes** [comment] 2020-10-02 02:08
This is fixed in `gatsby-source-wordpress-experimental@1.5.2`! Needed to check if the URL was already encoded before attempting to encode it. Your build still isn't succeeding because you have some images that legitimately 404. Once you update and run a build you should see errors about those. For now the build can't succeed past 404's so you'll have to fix those. Follow #70 if you're interested in allowing 404's. Cheers!

**Closed by TylerBarnes** 2020-10-02 02:08 UTC
Labels: address before stable release, bug: images, needs reproduction

**Comment by TylerBarnes** [comment] 2020-10-09 00:28
PS 404 images no longer fail the build in develop 🙌

**Comment by patrikarvidsson** [comment] 2020-10-10 18:44
> PS 404 images no longer fail the build in develop 🙌 

Fantastic! Thank you so much for looking into this so quickly!
