### ISSUE TITLE
Critical error sourceNodes.sourceNodes build step.

### ISSUE THREAD

**Issue by oliverfeher** [gatsbyjs/gatsby-source-wordpress-experimental#75] opened 2020-07-20 20:24 UTC
I have a running WP development instance hosted on pantheon and I'm trying to use the DB for localhost.

This is my gatsby-config.js
`{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://my-site-hosted-on-pantheon/graphql`,
      },
    }`

and this is my error msg.
`ERROR 

 gatsby-source-wordpress 

        Encountered a critical error when running the sourceNodes.sourceNodes build step.
        See above for more information.

not finished source and transform nodes - 4.391s
not finished  gatsby-source-wordpress  fetching nodes - 4.336s - 59 total
not finished  gatsby-source-wordpress  Category - 4.344s
not finished  gatsby-source-wordpress  Comment - 4.347s
not finished  gatsby-source-wordpress  Page - 4.330s
not finished  gatsby-source-wordpress  Post - 4.326s
not finished  gatsby-source-wordpress  Tag - 4.322s

**Comment by woodwoerk** [comment] 2020-07-21 14:04
Hey @oliverfeher !

Do you also see `error Cannot destructure property 'id' of 'undefined' as it is undefined.` in your log output? If so this might be a duplicate of #72

**Comment by oliverfeher** [comment] 2020-07-21 14:08
Hi @woodwoerk !

I haven't seen that error. Every time I'm trying to run `gatsby develop` it will throw this error...

This is my most recent gatsby-config.js

`{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: "https://my-site.pantheonsite.io/graphql",
        verbose: true,
        schema: {
          queryDepth: 5,
          typePrefix: "Wp",
          timeout: 30000,
        }
      },
    }
`

and I get this error..

`  Encountered a critical error when running the sourceNodes.sourceNodes build step.
    See above for more information.`

**Comment by TylerBarnes** [comment] 2020-07-21 22:34
Hi @oliverfeher , it's hard to tell what it could be from the description. Can you share a reproduction repo or a the GraphQL endpoint url so I can use it to debug? If it's private you can send it to me at tyler@gatsbyjs.com

Thanks!

**Comment by TylerBarnes** [comment] 2020-07-22 02:16
Oliver DM'ed me on twitter, it appears the problem here is a WPGraphQL bug where JSON in post content seems to cause an error (my best guess) and that wasn't being caught by this plugin. I DM'ed @jasonbahl the details and we'll work out an upstream fix for this. I'll also update the error handling here to catch this error more gracefully in the meantime 👍

**Comment by oliverfeher** [comment] 2020-07-22 02:18
@TylerBarnes , thank you so much for your help!

**Comment by TylerBarnes** [comment] 2020-07-22 02:45
Anytime, always happy to help :)

**Comment by jasonbahl** [comment] 2020-07-22 14:01
@oliverfeher I tried the endpoint that @TylerBarnes shared with me and it appears it's not a valid GraphQL endpoint. Did you de-activate WPGraphQL on that endpoint?

**Comment by oliverfeher** [comment] 2020-07-22 14:11
> @oliverfeher I tried the endpoint that @TylerBarnes shared with me and it appears it's not a valid GraphQL endpoint. Did you de-activate WPGraphQL on that site?

@jasonbahl , is there a possibility that we could DM? https://twitter.com/Oliver92F

**Comment by TylerBarnes** [comment] 2020-07-24 17:06
Via DM we were able to narrow the issue down to a single post_content field which contained JSON data. We weren't able to reproduce by copy/pasting that JSON data into our test WP instances, even after attempting to apply a post_content filter to JSON parse the data. Our best guess is that there is some custom logic in this WP instance that is filtering the content or something else to cause GraphQL to return an empty string instead of a JSON response for that post (when the content field is queried).

Next steps are for @oliverfeher's backend engineer to try to prevent this logic from running on that post during a graphql request.

@oliverfeher if it's possible for us to get a copy of this WP instance we're happy to continue debugging and helping out with this, but I'm closing this issue as it's not a bug in the source plugin or in WPGraphQL.

Thanks again for all your patience @oliverfeher !

**Closed by TylerBarnes** 2020-07-24 17:06 UTC
Labels: needs reproduction
