### ISSUE TITLE
Fetching images at build time causes an error

### ISSUE THREAD

**Issue by shosasaki0** [gatsbyjs/gatsby-source-wordpress-experimental#53] opened 2020-07-14 03:43 UTC
Hi

I'm about to try out a great plugin, but when I push the first image, it says An error has occurred and I am unable to proceed.

The error is this.

```
already re-queued /wp-content/uploads/2020/06/test.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to undefined
```
It's not just this image that is showing an error.

The image exists and it can be seen when I hit the URL.
The images are all over 1MB in size, is there a reason for this?
Changing GATSBY_CONCURRENT_DOWNLOAD did not solve the problem It was.

It probably stops here.
```
source and transform nodes
gatsby-source-wordpress  fetching nodes — 258 total
gatsby-source-wordpress  creating nodes
gatsby-source-wordpress  MediaItem — fetched 200
```

Thank you for all the work on this plugin!

Regards,
sasaki

**Comment by TylerBarnes** [comment] 2020-07-14 22:03
Hi @shosasaki0 , thanks for opening an issue!
It's hard to tell what it could be from your description. Are you able to share a reproduction repo and live WPGraphQL API endpoint that I can use to debug?

Thanks!

**Comment by lupoair** [comment] 2020-07-21 10:30
@TylerBarnes We are having the same issue with out of the box gatsy + gatsby-source-wordpress-experimental setup up to our live endpoint. Can send endpoint for testing as PM.

**Comment by TylerBarnes** [comment] 2020-09-18 23:43
Hi @lupoair , it's really hard to keep track of which GraphQL endpoints map to which GH issues. Are you able to send your API again?

BTW I think this issue might be resolved now. It looks like the url it's trying to fetch is a relative url `/wp-content/uploads/2020/06/test.jpg`. The plugin more recently detects this and adds the WP url to the request.

**Comment by kawamataryo** [comment] 2020-09-24 22:22
Hi. I have the same problem when `gatsby develop` commands.
Is there a solution?

## Environment to reproduce
Repo: https://github.com/kawamataryo/practice-gatsby-source-wordpress-experimental

Wordpress: v5.51
WP Gatsby: 0.4.16
WP GraphQL: 0.12.3

### log

```
~/g/g/k/practice-gatsby-source-wordpress-experimental ❯❯❯ gatsby develop
success open and validate gatsby-configs - 0.037s
success load plugins - 1.697s
success onPreInit - 0.034s
success initialize cache - 0.012s
success copy gatsby files - 0.044s
success onPreBootstrap - 0.019s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 0.981s
success createSchemaCustomization - 2.054s
success  gatsby-source-wordpress  Comment - 0.325s - fetched 0
success  gatsby-source-wordpress  Menu - 1.421s - fetched 3
success  gatsby-source-wordpress  Post - 1.893s - fetched 70
success  gatsby-source-wordpress  Tag - 1.936s - fetched 0
success  gatsby-source-wordpress  PostFormat - 1.992s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.998s - fetched 3
success  gatsby-source-wordpress  UserRole - 1.999s - fetched 0
success  gatsby-source-wordpress  Category - 2.128s - fetched 4
success  gatsby-source-wordpress  Page - 2.203s - fetched 8
success  gatsby-source-wordpress  MenuItem - 2.280s - fetched 24
success  gatsby-source-wordpress  ContentType - 2.298s - fetched 3
success  gatsby-source-wordpress  User - 2.252s - fetched 2
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing /wp-content/uploads/2017/03/5642fae96ade14100be5-1.jpg to the end of the request queue.
info Previously retried 4 times already.
info

already re-queued /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It's currently set to undefined



 ERROR 

url passed to create-remote-file-node is either missing or not a proper web uri: /wp-content/uploads/2017/02/466bd28e5ab06680a011.jpg

not finished source and transform nodes - 147.741s
not finished  gatsby-source-wordpress  fetching nodes - 147.713s - 119 total
not finished  gatsby-source-wordpress  creating nodes - 145.368s
not finished  gatsby-source-wordpress  MediaItem - 145.369s - fetched 2
```

**Comment by shosasaki0** [comment] 2020-10-02 10:31
@TylerBarnes
Sorry for the late response.
As you mentioned, I had some code on my WP that outputs a relative path.
So I deleted that code but it still doesn’t seem to work.
My current version is 1.5.3.
```
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Yipso.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_QhYAZ.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_M5JRH.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Fphj4.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_58Si5.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_szBuI.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_S2Dti.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_NLkTQ.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_ONnKd.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_GPIAp.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_w5mJy.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_unU9J.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zioGD.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_IKWdS.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zhEwR.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_x8xGD.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_149_f7de7.svg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_waOnE.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Xbkwh.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_LzSVA.png to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_tnknL.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_7wEXJ.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_SpTI1-scaled.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_FMzhN.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_QhYAZ.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Yipso.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_S2Dti.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_GPIAp.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_ONnKd.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Fphj4.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_NLkTQ.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_szBuI.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_58Si5.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_x8xGD.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_M5JRH.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zioGD.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_w5mJy.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_IKWdS.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zhEwR.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_waOnE.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Xbkwh.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_tnknL.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_unU9J.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_7wEXJ.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_FMzhN.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_149_f7de7.svg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_QhYAZ.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_LzSVA.png to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_SpTI1-scaled.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Yipso.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Fphj4.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_ONnKd.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_58Si5.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_NLkTQ.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_GPIAp.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_S2Dti.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_x8xGD.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_szBuI.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zhEwR.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_M5JRH.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_zioGD.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_waOnE.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_w5mJy.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_tnknL.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_FMzhN.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_IKWdS.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_unU9J.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_Xbkwh.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://example.com/wp-content/uploads/2020/09/post_1705_7wEXJ.jpg to the end of the request queue.
info Previously retried 4 times already.
info
already re-queued https://example.com/wp-content/uploads/2020/09/post_1705_QhYAZ.jpg 5 times :( sorry.
Try lowering process.env.GATSBY_CONCURRENT_DOWNLOAD.
It’s currently set to undefined
ERROR
failed to process https://example.com/wp-content/uploads/2020/09/post_1705_QhYAZ.jpg
TypeError: Parameter `auth` is deprecated. Use `username` / `password` instead.
```
I\`m sorry I couldn`t provide you a reproduction repo.
Is there a way I could test the above and debug?

**Comment by shosasaki0** [comment] 2020-10-03 08:53
@TylerBarnes 
Perhaps we have found the cause.
Please be patient as I create a pull request. :)

**Comment by jdselig** [comment] 2020-10-06 18:28
Hey guys! For what it's worth, we're seeing the same problem; looks like @shosasaki0 's fix would work though. Let me know if there's anything I can do to help get that merged :D

**Comment by TylerBarnes** [comment] 2020-10-06 18:33
Great that this is such a simple fix! Thank you @shosasaki0 for the PR and @jdselig for chiming in. I'm trying to not work on too many issues at once but this is next on my list after the one I'm currently working on. Thanks for your patience!

**Comment by jdselig** [comment] 2020-10-06 18:57
Awesome, thanks @TylerBarnes—keep up the great work! 😀

**Closed** 2020-10-08 01:51 UTC
Labels: address before stable release, needs reproduction

**Comment by TylerBarnes** [comment] 2020-10-08 01:52
A fix is published in `gatsby-source-wordpress-experimental@1.6.2`. Thanks @shosasaki0 and @jdselig !

**Comment by shosasaki0** [comment] 2020-10-08 04:04
Thank you for your quick fix @TylerBarnes!
I appreciate you chiming in @jdselig.

**Comment by uzomao** [comment] 2020-10-14 22:27
Hey @TylerBarnes @shosasaki0 I've upgraded to 1.7.5 but still seem to be running into this issue
