### ISSUE TITLE
Advanced Custom Fields are detected on normal WP Post but not on custom content type

### ISSUE THREAD

**Issue by jose-donato** [gatsbyjs/gatsby-source-wordpress-experimental#119] opened 2020-08-12 20:26 UTC
In my project I have multiple content types:
- default ones: posts and pages
- programs (custom content type created with register_post_type)
- podcasts (custom content type created with register_post_type)

This plugin is detecting the advanced custom fields from Posts but not from the other custom content types (programs and podcasts). Is this bug known?

Greetings

**Comment by TylerBarnes** [comment] 2020-08-12 23:32
Hi @jose-donato , thanks for opening this issue!
It's hard to say from your description but my first instinct is that this is happening due to not adding those types to WPGraphQL.
When you register a post type you need to set it to `'show_in_graphql' => true`. When you add acf fields you have to add them to a specific post type via the location rules. There are some location rules which don't work in a Graph and I believe currently the only accurate one is adding field groups directly to entire post types. So if you for example have a field group attached to a post type AND a template, I believe that wont show up. https://github.com/wp-graphql/wp-graphql-acf#why-arent-all-location-rules-supported

To determine wether this is a bug or misconfiguration, follow the steps here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#missing-data-in-gatsby

**Comment by jose-donato** [comment] 2020-08-12 23:44
I will try later to provide some more info. Sorry about that.

I added the `'show_in_graphql' => true` when registering the custom content type and I can query them in the local Graphiql (in the wordpress dashboard with WPGraphiql)

**Comment by donnervetter** [comment] 2020-08-13 15:27
Hey everyone, i'm having a similar problem - Advanced Custom Fields appear only on posts but not on pages.

**Comment by TylerBarnes** [comment] 2020-08-13 15:34
If someone can provide a reproduction /graphql endpoint that would go a long way here. Thanks!

**Comment by TylerBarnes** [comment] 2020-08-13 15:35
Feel free to email it to me with a reference to this issue if it's a private endpoint. (tyler@gatsbyjs.com)

**Comment by jose-donato** [comment] 2020-08-13 21:24
Just emailed you, @TylerBarnes

**Comment by jball23** [comment] 2020-08-17 03:00
I am using CPT-UI and was having the same issue because it only gave the option to show in the REST api, not GraphQL.  This is a very minimal WP plugin I found that will add the "show in graphql" fields on your custom post type.  Works like a charm.

https://github.com/wp-graphql/wp-graphql-custom-post-type-ui

**Comment by robmarshall** [comment] 2020-08-29 23:19
I am having this same issue. The custom post type is showing up in GraphQL, but the ACF fields are not. 

All of the correct settings are checked, so that the fields should be shown. I have fields showing up in a regular page, but not a CPT.

**Comment by TylerBarnes** [comment] 2020-09-18 22:24
Apologies for the delayed response here, I was out on vacation for a few weeks. This is on my radar

**Comment by TylerBarnes** [comment] 2020-10-02 01:18
Looks like this was either fixed incidentally by another release, or I'm not going through the right steps to reproduce.

@jose-donato the endpoint you emailed me seems to redirect to localhost so I can't use it to debug.
@robmarshall are you still able to invite me to that repo?

Here it is working:

<img width="1167" alt="Screen Shot 2020-10-01 at 6 15 19 PM" src="https://user-images.githubusercontent.com/14190743/94878450-48121880-0412-11eb-9b85-cc37856e6a1a.png">

**Comment by robmarshall** [comment] 2020-10-02 04:52
Hi Tyler. It seems for me that this issue has been resolved. Not sure when though.

**Comment by TylerBarnes** [comment] 2020-10-02 15:51
Woo! That's great to hear :D I have made improvements to how data resolves since this issue was opened, so that could explain it 👍 

Thanks for verifying

**Closed by TylerBarnes** 2020-10-02 15:51 UTC
Labels: address before stable release, bug: missing data
