### ISSUE TITLE
Request failed with status code 500 

### ISSUE THREAD

**Issue by nguyenhuutinh** [gatsbyjs/gatsby-source-wordpress-experimental#329] opened 2020-11-30 10:24 UTC
Hello,
I got this error when I tried to build our website with 1000 products

```
error  gatsby-source-wordpress  Request failed with status code 500 

Error occured while fetching nodes of the "Product" type.
```

Do you know how to debug this?

Thanks

```
info  gatsby-source-wordpress  GraphQL vars: {"first":100,"url":"http://v3.ruounhapchinhhang.vn/graphql","after":null}
error  gatsby-source-wordpress  GraphQL query: query NODE_LIST_QUERY($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    nodes {
      ... on VariableProduct {
        backorders
        backordersAllowed
        commentCount
        commentStatus
        content
        crossSell(first: 100) {
          nodes {
            id
            __typename
          }
        }
        dateGmt
        defaultAttributes(first: 100) {
          nodes {
            attributeId
            id
            label
            name
            value
          }
        }
        desiredSlug
        enclosure
        featuredImage {
          node {
            __typename
            id
          }
        }
        featuredImageDatabaseId
        featuredImageId
        guid
        height
        lastEditedBy {
          node {
            id
          }
        }
        length
        manageStock
        metaData {
          id
          key
          value
        }
        modifiedGmt
        price
        priceRaw
        regularPrice
        salePrice
        shippingClassId
        shippingRequired
        shippingTaxable
        soldIndividually
        stockQuantity
        stockStatus
        taxClass
        taxStatus
        template {
          templateName
          __typename
        }
        uri
        variations(first: 100) {
          nodes {
            attributes(first: 100) {
              nodes {
                attributeId
                id
                label
                name
                value
              }
            }
            backorders
            backordersAllowed
            catalogVisibility
            contentType {
              node {
                id
              }
            }
            databaseId
            date
            dateGmt
            dateOnSaleFrom
            dateOnSaleTo
            description
            desiredSlug
            downloadExpiry
            downloadLimit
            downloadable
            downloads {
              allowedFileType
              downloadId
              file
              fileExists
              fileExt
              filePathType
              fileType
              name
            }
            enclosure
            featuredImage {
              node {
                __typename
                id
              }
            }
            featuredImageDatabaseId
            featuredImageId
            guid
            hasAttributes
            height
            id
            image {
              __typename
              id
            }
            lastEditedBy {
              node {
                id
              }
            }
            length
            link
            manageStock
            menuOrder
            metaData {
              id
              key
              value
            }
            modified
            modifiedGmt
            name
            onSale
            wpParent: parent {
              node {
                id
                ...VariableProductFragment
              }
            }
            price
            purchasable
            purchaseNote
            regularPrice
            salePrice
            shippingClass
            shippingClasses(first: 100) {
              nodes {
                id
              }
            }
            sku
            slug
            status
            stockQuantity
            stockStatus
            taxClass
            taxStatus
            template {
              templateName
              __typename
            }
            type
            uri
            virtual
            visibleProducts(first: 100) {
              nodes {
                id
              }
            }
            weight
            width
          }
        }
        weight
        width
      }
      ... on ExternalProduct {
        buttonText
        commentCount
        commentStatus
        content
        dateGmt
        defaultAttributes(first: 100) {
          nodes {
            attributeId
            id
            label
            name
            value
          }
        }
        desiredSlug
        enclosure
        externalUrl
        featuredImage {
          node {
            __typename
            id
          }
        }
        featuredImageDatabaseId
        featuredImageId
        guid
        lastEditedBy {
          node {
            id
          }
        }
        metaData {
          id
          key
          value
        }
        modifiedGmt
        price
        priceRaw
        regularPrice
        salePrice
        taxClass
        taxStatus
        template {
          templateName
          __typename
        }
        uri
      }
      ... on GroupProduct {
        addToCartDescription
        addToCartText
        commentCount
        commentStatus
        content
        dateGmt
        defaultAttributes(first: 100) {
          nodes {
            attributeId
            id
            label
            name
            value
          }
        }
        desiredSlug
        enclosure
        featuredImage {
          node {
            __typename
            id
          }
        }
        featuredImageDatabaseId
        featuredImageId
        guid
        lastEditedBy {
          node {
            id
          }
        }
        metaData {
          id
          key
          value
        }
        modifiedGmt
        price
        products(first: 100) {
          nodes {
            id
            __typename
          }
        }
        template {
          templateName
          __typename
        }
        uri
      }
      ... on SimpleProduct {
        backorders
        backordersAllowed
        commentCount
        commentStatus
        content
        crossSell(first: 100) {
          nodes {
            id
            __typename
          }
        }
        dateGmt
        defaultAttributes(first: 100) {
          nodes {
            attributeId
            id
            label
            name
            value
          }
        }
        desiredSlug
        downloadExpiry
        downloadLimit
        downloadable
        downloads {
          allowedFileType
          downloadId
          file
          fileExists
          fileExt
          filePathType
          fileType
          name
        }
        enclosure
        featuredImage {
          node {
            __typename
            id
          }
        }
        featuredImageDatabaseId
        featuredImageId
        guid
        height
        lastEditedBy {
          node {
            id
          }
        }
        length
        manageStock
        metaData {
          id
          key
          value
        }
        modifiedGmt
        price
        priceRaw
        regularPrice
        salePrice
        shippingClassId
        shippingRequired
        shippingTaxable
        soldIndividually
        stockQuantity
        stockStatus
        taxClass
        taxStatus
        template {
          templateName
          __typename
        }
        uri
        virtual
        weight
        width
      }
      attributes(first: 100) {
        nodes {
          attributeId
          id
          label
          name
          options
          position
          scope
          variation
          visible
          __typename
          ... on GlobalProductAttribute {
            slug
            terms(first: 100) {
              nodes {
                id
                __typename
              }
            }
          }
        }
      }
      averageRating
      catalogVisibility
      contentType {
        node {
          id
        }
      }
      databaseId
      date
      dateOnSaleFrom
      dateOnSaleTo
      description
      featured
      galleryImages(first: 100) {
        nodes {
          __typename
          id
        }
      }
      globalAttributes(first: 100) {
        nodes {
          attributeId
          id
          label
          name
          options
          position
          scope
          slug
          terms(first: 100) {
            nodes {
              id
              __typename
            }
          }
          variation
          visible
        }
      }
      id
      image {
        __typename
        id
      }
      link
      localAttributes(first: 100) {
        nodes {
          attributeId
          id
          label
          name
          options
          position
          scope
          variation
          visible
        }
      }
      menuOrder
      modified
      name
      onSale
      paDungTiches(first: 100) {
        nodes {
          id
        }
      }
      paNongDos(first: 100) {
        nodes {
          id
        }
      }
      paPhanLoais(first: 100) {
        nodes {
          id
        }
      }
      paThuongHieus(first: 100) {
        nodes {
          id
        }
      }
      paTuoiRuous(first: 100) {
        nodes {
          id
        }
      }
      paXuatXus(first: 100) {
        nodes {
          id
        }
      }
      wpParent: parent {
        id
        __typename
      }
      productCategories(first: 100) {
        nodes {
          id
        }
      }
      productTags(first: 100) {
        nodes {
          id
        }
      }
      productTypes(first: 100) {
        nodes {
          id
        }
      }
      purchasable
      purchaseNote
      related(first: 100) {
        nodes {
          id
          __typename
        }
      }
      reviewCount
      reviews(first: 100) {
        averageRating
        nodes {
          id
        }
      }
      reviewsAllowed
      seo {
        breadcrumbs {
          text
          url
        }
        canonical
        cornerstone
        focuskw
        metaDesc
        metaKeywords
        metaRobotsNofollow
        metaRobotsNoindex
        opengraphAuthor
        opengraphDescription
        opengraphImage {
          __typename
          id
        }
        opengraphModifiedTime
        opengraphPublishedTime
        opengraphPublisher
        opengraphSiteName
        opengraphTitle
        opengraphType
        opengraphUrl
        schema {
          articleType
          pageType
        }
        title
        twitterDescription
        twitterImage {
          __typename
          id
        }
        twitterTitle
      }
      shippingClasses(first: 100) {
        nodes {
          id
        }
      }
      shortDescription
      sku
      slug
      status
      totalSales
      type
      upsell(first: 100) {
        nodes {
          id
          __typename
        }
      }
      visibleProducts(first: 100) {
        nodes {
          id
        }
      }
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
fragment VariableProductFragment on VariableProduct {
  attributes(first: 100) {
    nodes {
      attributeId
      id
      label
      name
      options
      position
      scope
      variation
      visible
      __typename
      ... on GlobalProductAttribute {
        slug
        terms(first: 100) {
          nodes {
            id
            __typename
          }
        }
      }
    }
  }
  averageRating
  backorders
  backordersAllowed
  catalogVisibility
  commentCount
  commentStatus
  content
  contentType {
    node {
      id
    }
  }
  crossSell(first: 100) {
    nodes {
      id
      __typename
    }
  }
  databaseId
  date
  dateGmt
  dateOnSaleFrom
  dateOnSaleTo
  defaultAttributes(first: 100) {
    nodes {
      attributeId
      id
      label
      name
      value
    }
  }
  description
  desiredSlug
  enclosure
  featured
  featuredImage {
    node {
      __typename
      id
    }
  }
  featuredImageDatabaseId
  featuredImageId
  galleryImages(first: 100) {
    nodes {
      __typename
      id
    }
  }
  globalAttributes(first: 100) {
    nodes {
      attributeId
      id
      label
      name
      options
      position
      scope
      slug
      terms(first: 100) {
        nodes {
          id
          __typename
        }
      }
      variation
      visible
    }
  }
  guid
  height
  id
  image {
    __typename
    id
  }
  lastEditedBy {
    node {
      id
    }
  }
  length
  link
  localAttributes(first: 100) {
    nodes {
      attributeId
      id
      label
      name
      options
      position
      scope
      variation
      visible
    }
  }
  manageStock
  menuOrder
  metaData {
    id
    key
    value
  }
  modified
  modifiedGmt
  name
  onSale
  paDungTiches(first: 100) {
    nodes {
      id
    }
  }
  paNongDos(first: 100) {
    nodes {
      id
    }
  }
  paPhanLoais(first: 100) {
    nodes {
      id
    }
  }
  paThuongHieus(first: 100) {
    nodes {
      id
    }
  }
  paTuoiRuous(first: 100) {
    nodes {
      id
    }
  }
  paXuatXus(first: 100) {
    nodes {
      id
    }
  }
  wpParent: parent {
    id
    __typename
  }
  price
  priceRaw
  productCategories(first: 100) {
    nodes {
      id
    }
  }
  productTags(first: 100) {
    nodes {
      id
    }
  }
  productTypes(first: 100) {
    nodes {
      id
    }
  }
  purchasable
  purchaseNote
  regularPrice
  related(first: 100) {
    nodes {
      id
      __typename
    }
  }
  reviewCount
  reviews(first: 100) {
    averageRating
    nodes {
      id
    }
  }
  reviewsAllowed
  salePrice
  seo {
    breadcrumbs {
      text
      url
    }
    canonical
    cornerstone
    focuskw
    metaDesc
    metaKeywords
    metaRobotsNofollow
    metaRobotsNoindex
    opengraphAuthor
    opengraphDescription
    opengraphImage {
      __typename
      id
    }
    opengraphModifiedTime
    opengraphPublishedTime
    opengraphPublisher
    opengraphSiteName
    opengraphTitle
    opengraphType
    opengraphUrl
    schema {
      articleType
      pageType
    }
    title
    twitterDescription
    twitterImage {
      __typename
      id
    }
    twitterTitle
  }
  shippingClassId
  shippingClasses(first: 100) {
    nodes {
      id
    }
  }
  shippingRequired
  shippingTaxable
  shortDescription
  sku
  slug
  soldIndividually
  status
  stockQuantity
  stockStatus
  taxClass
  taxStatus
  template {
    templateName
    __typename
  }
  totalSales
  type
  upsell(first: 100) {
    nodes {
      id
      __typename
    }
  }
  uri
  visibleProducts(first: 100) {
    nodes {
      id
    }
  }
  weight
  width
}
```

**Comment by dipankarmaikap** [comment] 2020-11-30 20:14
I"m facing similar type of issue.
```
info  gatsby-source-wordpress  GraphQL vars: {"first":10,"url":"https://mysiteurl/graphql","after":null}
error  gatsby-source-wordpress  Request failed with status code 500 

Error occured while fetching nodes of the "Category" type.
```

I can see the query "Category" in graphiql-ide with in wordpress, If i switch to a different WordPress site it works but not in this specif site. Here is my settings

```
{
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: `https://mysiteurl/graphql`,
        schema: {
          timeout: 60000,
        },
        type: {
          __all: {
            limit: 10,
          },
        },
        debug: {
          graphql: {
            showQueryVarsOnError: true,
          },
        },
      },
    },
```

BTW this WordPress site has more than 10K posts. Default Twenty Twenty theme with "WP Gatsby" and "WP GraphQL" plugin, nothing else.

**Comment by TylerBarnes** [comment] 2020-11-30 23:39
Hi there! This plugin doesn't currently WooCommerce. We have plans to support it in the future, but we currently don't support it. 

This issue is a duplicate of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/85

https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/98 will likely also fix this issue in the future, but for now you'll want to follow the steps in #85 . We have a PR about to be merged which includes better error messages when this happens with steps on how to fix this but it's not merged yet.

**Closed by TylerBarnes** 2020-11-30 23:39 UTC
