### ISSUE TITLE
Bug: Source and transform nodes step never finishes after 1.4.1

### ISSUE THREAD

**Issue by gustavpursche** [gatsbyjs/gatsby-source-wordpress-experimental#197] opened 2020-10-02 08:13 UTC
After version `1.4.1` I run into the following problem:

```
kolle-on-xps :: Development/coaltransitions » yarn develop
yarn run v1.22.4
$ gatsby develop
success open and validate gatsby-configs - 0.066s
success load plugins - 0.701s
success onPreInit - 0.032s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.074s
success copy gatsby files - 0.017s
success onPreBootstrap - 0.015s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 1.276s
success createSchemaCustomization - 2.189s
success  gatsby-source-wordpress  fetch root fields - 1.591s
success  gatsby-source-wordpress  Category - 1.682s - fetched 1
success  gatsby-source-wordpress  Comment - 1.796s - fetched 0
success  gatsby-source-wordpress  Menu - 1.787s - fetched 2
success  gatsby-source-wordpress  Finding - 2.669s - fetched 8
success  gatsby-source-wordpress  NewsEntry - 2.942s - fetched 3
success  gatsby-source-wordpress  Post - 3.261s - fetched 1
success  gatsby-source-wordpress  MenuItem - 3.484s - fetched 8
success  gatsby-source-wordpress  PostFormat - 3.777s - fetched 0
success  gatsby-source-wordpress  ContentType - 3.892s - fetched 8
success  gatsby-source-wordpress  UserRole - 4.695s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 5.137s - fetched 3
success  gatsby-source-wordpress  ResearchProject - 5.527s - fetched 17
success  gatsby-source-wordpress  User - 6.000s - fetched 4
success  gatsby-source-wordpress  Page - 6.208s - fetched 13
success  gatsby-source-wordpress  Researcher - 8.610s - fetched 62
success  gatsby-source-wordpress  Tag - 11.001s - fetched 157
success  gatsby-source-wordpress  Publication - 11.071s - fetched 110
success Downloading remote files - 2.055s - 0/2 0.97/s
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/10/diw-weekly-report-41-2.png to the end of the request queue.
info Previously retried 2 times already.
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/11/1-s2-0-s2214629618306698-ga1_lrg.jpg to the end of the request queue.
info Previously retried 2 times already.
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/11/1-s2-0-s2214629618306698-ga1_lrg.jpg to the end of the request queue.
info Previously retried 3 times already.
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/10/diw-weekly-report-41-2.png to the end of the request queue.
info Previously retried 3 times already.
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/11/1-s2-0-s2214629618306698-ga1_lrg.jpg to the end of the request queue.
info Previously retried 4 times already.
info pushing https://admin.coaltransitions.org/wp-content/uploads/2019/10/diw-weekly-report-41-2.png to the end of the request queue.
info Previously retried 4 times already.
⠸ source and transform nodes
not finished source and transform nodes - 152.954s
not finished  gatsby-source-wordpress  fetching nodes - 152.913s - 399 total
not finished  gatsby-source-wordpress  creating nodes - 141.712s
not finished  gatsby-source-wordpress  MediaItem - 141.713s - fetched 2
```

```
kolle-on-xps :: Development/coaltransitions » npx gatsby info                                 

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 81.0
  npmPackages:
    gatsby: ^2.24.67 => 2.24.67
    gatsby-image: ^2.4.20 => 2.4.20
    gatsby-link: ^2.4.15 => 2.4.15
    gatsby-plugin-advanced-sitemap: ^1.5.6 => 1.5.6
    gatsby-plugin-manifest: ^2.4.33 => 2.4.33
    gatsby-plugin-netlify: ^2.3.16 => 2.3.16
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.38 => 2.6.38
    gatsby-plugin-styled-jsx: ^3.3.13 => 3.3.13
    gatsby-source-filesystem: ^2.3.32 => 2.3.32
    gatsby-source-wordpress-experimental: ^1.5.3 => 1.5.3
    gatsby-transformer-sharp: ^2.5.16 => 2.5.16
```

For a reproduction of the case you could checkout [this repository](https://github.com/zoff-kollektiv/coaltransitions). I've send you the required .env variables via email.

This is a continuation for  #181

**Comment by enx1998** [comment] 2020-10-02 08:20
In my case the problem comes up with 1.4.3 and later versions.

Thanks for your work ENx

**Comment by benknight** [comment] 2020-10-03 03:26
Unsure if related but I started to experience a similar issue right around this version. For me, the "Downloading remote files" hangs for ever, looking something like this:

```
⠼ source and transform nodes
⠇ source and transform nodes
⠦  gatsby-source-wordpress  fetching nodes — 557 total
⠇  gatsby-source-wordpress  creating nodes
⠇  gatsby-source-wordpress  MediaItem — fetched 200
[                            ]   157.679 s 0/495 0% Downloading remote files
```

I'm not sure why it's downloading remote files to begin with because previously with `useGatsbyImage` set to false, it wasn't downloading any images (desired behavior, since my WordPress installation has a massive media library)

**Comment by brandensilva** [comment] 2020-10-04 04:27
Also getting the 0% Downloading remote files that Ben is seeing. After the build attempts this 5 times it eventually fails.

**Comment by trietho** [comment] 2020-10-05 05:03
Downgrade your node version to node@12 will work (my case: v12.18.4), I think node 13 still work with auth=user:password https://nodejs.org/api/http.html#http_http_request_url_options_callback

**Comment by TylerBarnes** [comment] 2020-10-08 02:25
Turns out this was a dupe of #53
A fix is published in gatsby-source-wordpress-experimental@1.6.2. Thanks for your patience here!

**Closed by TylerBarnes** 2020-10-08 02:25 UTC
Labels: address before stable release, bug: images
