### ISSUE TITLE
Unable to start app when using Azure hosted Wordpress

### ISSUE THREAD

**Issue by SuperCiacho** [gatsbyjs/gatsby-source-wordpress-experimental#174] opened 2020-09-24 21:36 UTC
Using version 1.3.9, I'm not able to successfully run gatsby develop when URL targets Azure hosted Wordpress (as a App Service) and any post contains a picture.
When I remove featured or embedded images, app will run.
Also everything works fine with local instance of Wordpress. 

On Azure portal, there're no HTTP 4xx or 5xx requests.
There's no request blocked or something.

EDIT:
I just checked version 1.4.0, issue still exists., but there's small progress there.
When any of post has featured image set, then app doesn't start.
When there're no featured images, but post embeds image, app starts but image isn't displayed (alt text only).
Mentioned issues don't occur using WP local instance.

![obraz](https://user-images.githubusercontent.com/5670702/94202124-c4ae6f80-fec5-11ea-9b77-3bade44f8644.png)

**Comment by TylerBarnes** [comment] 2020-09-24 22:04
It looks like this is because of a relative img url, but this plugin should account for that.
Can you share the /graphql API URL where you're having this issue? That'll help me reproduce and fix it.

Thanks!

**Comment by SuperCiacho** [comment] 2020-09-25 07:50
@TylerBarnes 
Here you go:
http://playground-wordpress.azurewebsites.net/graphql

**Comment by hetkotak** [comment] 2020-09-28 03:54
I use Azure Hosted wordpress with media images and this plugin works perfectly for me.

**Comment by SuperCiacho** [comment] 2020-09-28 06:00
@hetkotak 
Could you share any information about Wordpress setup you have?
What app service plan do you use?

**Comment by TylerBarnes** [comment] 2020-09-29 18:43
Hi @SuperCiacho , thanks for sharing your API. It turns out this bug was unrelated to Azure and was a regression with images. If you upgrade to `gatsby-source-wordpress-experimental@1.4.5` it will be fixed. See #181 for more context.

Cheers!

**Closed by TylerBarnes** 2020-09-29 18:43 UTC
Labels: needs reproduction
