### ISSUE TITLE
Builds fail with a large number of posts

### ISSUE THREAD

**Issue by kellenmace** [gatsbyjs/gatsby-source-wordpress-experimental#128] opened 2020-08-17 16:16 UTC
## Issue
I have a WP site with a `run` custom post type. I built the frontend using `gatsby-source-wordpress-experimental` and Netlify builds were working great for a while. As the production app got more and more usage though, and the number of `run`s created by users got up above 1,800+ posts, the builds started failing.

The output of the Netlify deploy log looks like this:

```
...
success open and validate gatsby-configs - 0.042s
success load plugins - 0.738s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.012s
success initialize cache - 0.008s
success copy gatsby files - 0.082s
success onPreBootstrap - 0.010s
success [gatsby-source-wordpress] ingest WPGraphQL schema - 3.221s
success createSchemaCustomization - 4.481s

 ERROR

 gatsby-source-wordpress  Request failed with status code 500

Error occured while fetching nodes of the "User" type.

GraphQL request to https://api.runthroughhistory.com/wp/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

not finished source and transform nodes - 12.917s
not finished [gatsby-source-wordpress] fetching nodes - 12.825s - 157 total
...
```

## My Workaround

I did some troubleshooting and found that if I use `excludeFieldNames` to exclude the `run` post type altogether, builds start working again. Example:

```
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: process.env.GATSBY_WPGRAPHQL_URL,
        // `runs` is excluded here since the `fetching nodes` part of the
        // Gatsby build process fails if there are a lot of posts.
        excludeFieldNames: [`runs`],
      },
    },
```

This workaround works for my app, since I only fetch `run`s at runtime from the client and never fetch them at buildtime. It would certainly be problematic for developers who have a large number of posts that they do need access to at buildtime, however.

## Further Details

- My app is running gatsby-source-wordpress-experimental version 0.7.8
- In my testing, Netlify builds successfully completed if there were up to 1,677 posts. Builds started failing when there were 1,827 posts. So the max posts threshold seems to be somewhere within that range for builds on Netlify.

P.S. Thanks for all the great work on this new source plugin!

**Comment by robmarshall** [comment] 2020-08-30 12:51
Sounds like a timeout issue. Netlify has a build limit of 30 minutes.

**Comment by kellenmace** [comment] 2020-08-30 17:16
@robmarshall I agree. Because Gatsby is "aware" of all the queries that need to be run at buildtime, I think the ideal solution here would be for this source plugin to run some logic like this:
Is this post type being queried at buildtime? If so, fetch its posts. Otherwise, skip it.

That would have allowed my builds to complete, since as I mentioned, my app never queries the `run` post type at buildtime, so there's no reason for this source plugin to fetch all of its posts.

**Comment by robmarshall** [comment] 2020-08-30 21:40
That is a good point. I imagine there are a number of post types that are not queried such as users/settings (in smaller marketing sites) that have no need to be read. Would save precious time.

**Comment by TylerBarnes** [comment] 2020-09-18 21:55
Hi @kellenmace , If you update to the latest versions of all plugins this might actually go away. Previously some problematic fields were being fetched on users that slowed builds down quite a bit (users uploaded media items). So even if you weren't using those media items anywhere it was still fetching them, spiking the build time. What you're asking for though is in planning, check this issue out https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/98

Only queried for data will be fetched in production eventually.

**Comment by TylerBarnes** [comment] 2020-09-18 21:56
Also it'd be worth giving Gatsby Cloud a try, there's a free tier that will build your site really fast. It's much much faster than Netlify and it's also free. You can also deploy to Netlify as hosting.

**Comment by TylerBarnes** [comment] 2020-10-09 00:38
Looking at this again, I believe this is a duplicate of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/85

This wouldn't be a netlify timeout since the 500 error here is coming from WordPress.

**Closed by TylerBarnes** 2020-10-09 00:38 UTC
Labels: todo after v4 release
