### ISSUE TITLE
Request failed with status code 503

### ISSUE THREAD

**Issue by yudyananda** [gatsbyjs/gatsby-source-wordpress-experimental#142] opened 2020-08-31 09:25 UTC
Hi, i have trouble when running `gatsby develop` on my machine, it throw me ` gatsby-source-wordpress  Request failed with status code 503`. 

Here is the detail from my console
```bash
E:\USER\web_project\PROJECT\wp-gatsby> gatsby develop
Debugger listening on ws://127.0.0.1:9229/499ef276-9ffe-4c25-8cd1-fa645f386cf0
For help, see: https://nodejs.org/en/docs/inspector
success open and validate gatsby-configs - 0.054s
success load plugins - 2.341s
success onPreInit - 0.149s
success initialize cache - 0.087s
success copy gatsby files - 0.361s
success onPreBootstrap - 0.269s
warn  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.

success  gatsby-source-wordpress  ingest WPGraphQL schema - 4.900s
success createSchemaCustomization - 13.050s

 ERROR

 gatsby-source-wordpress  Request failed with status code 503

Error occured while fetching nodes of the "Comment" type.

GraphQL request to https://mywordpresss.com/graphql failed.

Please ensure the following statements are true
  - your WordPress URL is correct in gatsby-config.js
  - your server is responding to requests
  - WPGraphQL and WPGatsby are installed in your WordPress backend

not finished source and transform nodes - 13.478s
not finished  gatsby-source-wordpress  fetching nodes - 13.437s - 0 total
not finished  gatsby-source-wordpress  Category - 13.528s
not finished  gatsby-source-wordpress  Comment - 13.567s
not finished  gatsby-source-wordpress  ContentType - 13.600s
not finished  gatsby-source-wordpress  Coupon - 13.634s
not finished  gatsby-source-wordpress  Customer - 13.667s
not finished  gatsby-source-wordpress  MenuItem - 13.679s
not finished  gatsby-source-wordpress  Menu - 13.701s
not finished  gatsby-source-wordpress  Order - 13.720s
not finished  gatsby-source-wordpress  PaColor - 13.714s
not finished  gatsby-source-wordpress  PaSize - 13.718s
not finished  gatsby-source-wordpress  Page - 13.707s
not finished  gatsby-source-wordpress  PostFormat - 13.691s
not finished  gatsby-source-wordpress  Post - 13.640s
not finished  gatsby-source-wordpress  ProductCategory - 13.603s
not finished  gatsby-source-wordpress  ProductTag - 13.582s
not finished  gatsby-source-wordpress  ProductType - 13.558s
not finished  gatsby-source-wordpress  Product - 13.543s
not finished  gatsby-source-wordpress  Refund - 13.542s
not finished  gatsby-source-wordpress  ShippingClass - 13.528s
not finished  gatsby-source-wordpress  ShippingMethod - 13.510s
not finished  gatsby-source-wordpress  Tag - 13.484s
not finished  gatsby-source-wordpress  TaxRate - 13.450s
not finished  gatsby-source-wordpress  Taxonomy - 13.404s
not finished  gatsby-source-wordpress  UserRole - 13.346s
not finished  gatsby-source-wordpress  User - 13.313s
not finished  gatsby-source-wordpress  VisibleProduct - 13.274s
```

```javascript
// gatsby-config.js

require('dotenv').config();

module.exports = {
  /* Your site config here */
  plugins: [
    ...
    {
      resolve: `gatsby-source-wordpress-experimental`,
      options: {
        url: process.env.WP_GRAPHQL,
        /* schema: {
          //Prefixes all WP Types with "Wp" so "Post and allPost" become "WpPost and allWpPost".
          typePrefix: `Wp`,
        }, */
        develop: {
          //caches media files outside of Gatsby's default cache an thus allows them to persist through a cache reset.
          hardCacheMediaFiles: true,
        },
        type: {
          // Lets just pull 50 posts in development to make it easy on ourselves (aka. faster).
          // and we don't actually need more than 5000 in production for this particular site
          Post: {
            limit: process.env.NODE_ENV === `development` ? 50 : 5000,
          },
        },
      },
    },
  ],
}
```

I'm not realy sure what cause the error but this happen after intalling woocommerce in my wordpress side. Does gatsby-source-wordpress-experimental have support for woocommerce?

**Comment by TylerBarnes** [comment] 2020-09-18 21:01
Hey, thanks for opening this issue. I'm closing this as a duplicate of #147 . Please check that issue out and see if the solution there solves this problem for you as well.

**Closed by TylerBarnes** 2020-09-18 21:01 UTC
