### ISSUE TITLE
When i use an <img/> tag inside the custom HTML block of the Gutenberg editor to display an image, then the image is not getting displayed with its original height and width.

### ISSUE THREAD

**Issue by hasanm95** [gatsbyjs/gatsby-source-wordpress-experimental#250] opened 2020-10-27 11:06 UTC
preview > http://whizthemes.com/hasan/bootstrap/html-bundle

**Comment by TylerBarnes** [comment] 2020-11-12 21:47
Hi @hasanm95, thanks for reporting this! I'm closing this as a duplicate of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/151 but feel free to re-open this or let me know if you think that's incorrect.

**Closed by TylerBarnes** 2020-11-12 21:47 UTC
Labels: preview
