### ISSUE TITLE
Building keeps failing to get data from wordpress.

### ISSUE THREAD

**Issue by technobond** [gatsbyjs/gatsby-source-wordpress-experimental#147] opened 2020-09-03 18:54 UTC
> 8:49:54 PM: info  gatsby-source-wordpress 
> 8:49:54 PM: 	This is either your first build or the cache was cleared.
> 8:49:54 PM: 	Please wait while your WordPress data is synced to your Gatsby cache.
> 8:49:54 PM: 	Maybe now's a good time to get up and stretch? :D
> 8:49:56 PM: success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.412s
> 8:49:56 PM: success  gatsby-source-wordpress  ingest WPGraphQL schema - 3.374s
> 8:49:56 PM: success createSchemaCustomization - 5.373s
> 8:49:57 PM: error  gatsby-source-wordpress  Unable to connect to WPGraphQL.
> 8:49:57 PM: Error occured while fetching nodes of the "MediaPost" type.
> 8:49:57 PM: GraphQL request to https://techno.3box-advertising.com/graphql failed.
> 8:49:57 PM: Please ensure the following statements are true
> 8:49:57 PM:   - your WordPress URL is correct in gatsby-config.js
> 8:49:57 PM:   - your server is responding to requests
> 8:49:57 PM:   - WPGraphQL and WPGatsby are installed in your WordPress backend
> 8:49:57 PM: not finished source and transform nodes - 1.157s
> 8:49:57 PM: not finished  gatsby-source-wordpress  fetching nodes - 1.038s - 0 total
> 8:49:57 PM: not finished  gatsby-source-wordpress  AboutUsDetail - 1.037s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Branch - 1.036s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Category - 1.036s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Certification - 1.036s
> 8:49:57 PM: not finished  gatsby-source-wordpress  ColorType - 1.036s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Color - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Comment - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  ContactDetail - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  ContentType - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Country - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  DownloadCategory - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  DownloadCenter - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  HeadOffice - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  HomepageDetail - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  MediaPost - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  MenuItem - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Menu - 1.037s
> 8:49:57 PM: not finished  gatsby-source-wordpress  PageBackground - 1.037s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Page - 1.036s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Partner - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  PaymentDetail - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  PostFormat - 1.035s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Post - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Product - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  ProjectCategory - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Project - 1.034s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Tag - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  Taxonomy - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  TermsAndCondition - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  UserRole - 1.033s
> 8:49:57 PM: not finished  gatsby-source-wordpress  User - 1.033s

Everytime my website try to build it never finishes and i cant tell what the problem is.. any idea?

**Comment by petrmrkvicka** [comment] 2020-09-04 17:43
Hi @technobond 

Your console output says the following
``` 
8:49:57 PM: Please ensure the following statements are true
8:49:57 PM: - your WordPress URL is correct in gatsby-config.js
8:49:57 PM: - your server is responding to requests
8:49:57 PM: - WPGraphQL and WPGatsby are installed in your WordPress backend
```
Did you check all these things? Also, the URL has to lead to your graphql endpoint e.g. www.website.com/graphql

**Comment by TylerBarnes** [comment] 2020-09-17 23:14
@petrmrkvicka that's a good suggestion but I believe in this case the GraphQL url has been set which is why we can see all the different gql types listed in the output.

The issue here might be that your server is being overwhelmed by all the requests but it's hard to tell from the description here. Can you share you GraphQL api url with me by emailing tyler@gatsbyjs.com?

Thanks!

**Comment by yudyananda** [comment] 2020-09-19 02:08
@TylerBarnes  #142 is preety similiar with this issue, but in my case the request failed after i installed Woocommerce in my Wordpress side. without woocomerce the request is working like a charm.

**Comment by TylerBarnes** [comment] 2020-09-21 18:04
@yudyananda it's likely still the same problem and the issue is that Woo adds additional resource usage to each request. Try this https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#wordpress-50-errors and https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md#node-sourcing-timeouts And let me know if changing either of those settings helps.

Long term I want to automate this configuration as it can be really problematic for folks. See https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/66 for more info

**Comment by andreasbroch2** [comment] 2020-09-21 19:36
I have tried fixing the issue schema.perpage without any luck. 

How can I change the GATSBY_CONCURRENT_DOWNLOAD env variable? i cant find it anywhere?

**Comment by TylerBarnes** [comment] 2020-09-21 19:39
Hi @andreasbroch2 , the option should be schema.perPage instead of schema.perpage (just to be sure). For the environment variable you'll have to set it yourself https://www.gatsbyjs.com/docs/environment-variables/. Let me know if you need more help with it or if it doesn't work. In the future this part will be a lot easier, but it can be tricky right now

**Comment by andreasbroch2** [comment] 2020-09-21 19:49
I did it correct in my code :) 
I can set the variable in the env file, but it is not being used anywhere in the code? 
Is setting GATSBY_CONCURRENT_DOWNLOAD=10 in the env file enough? Shouldnt that variable be used in the config to do something. When i search my entire folder, i cant see the variable being used anywhere

**Comment by TylerBarnes** [comment] 2020-09-21 19:52
It's being used here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/a61d9153e8cc7fce84c97d0cc51b8e8cb2726761/src/steps/source-nodes/fetch-nodes/fetch-nodes.js as well as a few other places. I'm considering moving this into a plugin option to simplify things a bit.

**Comment by TylerBarnes** [comment] 2020-09-21 20:03
Sorry, just realized I didn't answer the first half of your question :p give 10 a shot, then 5, then 1.

**Comment by TylerBarnes** [comment] 2020-11-19 01:51
Closing this as a duplicate of https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/85

**Closed by TylerBarnes** 2020-11-19 01:51 UTC
Labels: address before stable release, needs reproduction
