### ISSUE TITLE
Gatsby build not showing updated menu items

### ISSUE THREAD

**Issue by ssoney200** [gatsbyjs/gatsby-source-wordpress-experimental#211] opened 2020-10-09 12:50 UTC
I have an issue where menus items do not update after Gatsby build.  It's obviously related to broswer caching, as when I view in incognito, the updated menu items are viewable. 

What is the best way to manage this so that users who have already been on the site can see the new menu items? I saw in another article that removing gatsby-plugin-offline fixed the issue as it was related to the service worker but this had no affect for me.

I also tried another route that a different article suggested using gatbsby-plugin-netlify cache to require 'must-validate' which also didn't help

```{
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {
          "/**/*.html": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/page-data/*.json": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/app-data.json": [
            "cache-control: public",
            "cache-control: max-age=0",
            "cache-control: must-revalidate",
          ],
          "/static/*": [
            "cache-control: public",
            "cache-control: max-age=31536000",
            "cache-control: immutable",
          ],
        },
        allPageHeaders: [], // option to add headers for all pages. `Link` headers are transformed by the below criteria
        mergeSecurityHeaders: true, // boolean to turn off the default security headers
        mergeLinkHeaders: true, // boolean to turn off the default gatsby js headers
        mergeCachingHeaders: true, // boolean to turn off the default caching headers
        transformHeaders: (headers, path) => headers, // optional transform for manipulating headers under each path (e.g.sorting), etc.
        generateMatchPathRewrites: true, // boolean to turn off automatic creation of redirect rules for client only paths
      },
    },```

I tried a further piece of advice recommending to add to gatsby-brower.js the following line, which also didn't help, so running out of ideas.

`exports.onServiceWorkerUpdateReady = () => window.location.reload(true);`

Any advice to manage help would be warmly received.

Thanks,
Jamie

**Comment by ssoney200** [comment] 2020-10-13 10:44
Does anyone have any advice on this? We have production site at https://glion.edu/ that is always showing outdated (cached) menus after build unless you view in incognito window which obviously most users don't do.

On normal page load (cached):
![Screenshot 2020-10-13 at 11 35 43](https://user-images.githubusercontent.com/7794363/95850114-3dc41880-0d48-11eb-9642-92bcf2e60b56.png)

In incognito (you can see menu items updated under work with us). 
<img width="1624" alt="Screenshot 2020-10-13 at 11 36 53" src="https://user-images.githubusercontent.com/7794363/95850229-6b10c680-0d48-11eb-82df-58a1390d1f5d.png">

Our clients are making changes fairly frequently, and also have a lot of repeat visitors so we need a solution to resolve issue with them seeing outdated menus.

Thanks,
Jamie

**Comment by TylerBarnes** [comment] 2020-10-15 17:11
Hi @ssoney200 , sorry for the delayed response here. If this is caused by gatsby-plugin-offline, removing the offline plugin isn't enough as you (or anyone else who visited your site) will still have the service worker registered in your browser while the offline plugin was enabled.
You need this plugin to fully remove it https://www.npmjs.com/package/gatsby-plugin-remove-serviceworker

I'm closing this issue as it appears it's not related to this plugin, but I'd encourage you to open an issue on the GatsbyJS repo if you're still having troubles.

Thanks!

**Closed by TylerBarnes** 2020-10-15 17:11 UTC
