### ISSUE TITLE
Cannot add the latest package due to allocation failure

### ISSUE THREAD

**Issue by pepsighan** [gatsbyjs/gatsby-source-wordpress-experimental#18] opened 2020-06-05 04:24 UTC
While adding/installing the following version, yarn fails due to allocation failure. 
Version: `"gatsby-source-wordpress-experimental": "^0.7.8"`.

The last version that worked was `0.6.1` and started failing with `0.7.0`.

```
yarn install v1.22.4
[1/4] Resolving packages...
warning gatsby-source-wordpress-experimental > gatsby > gatsby-cli > gatsby-recipes > graphql-tools > @graphql-tools/relay-operation-optimizer > relay-compiler > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.1" has incorrect peer dependency "react-refresh@^0.8.2".
warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > gatsby-plugin-theme-ui@0.3.0" has incorrect peer dependency "theme-ui@^0.2.0".
warning " > gatsby-source-wordpress-experimental@0.7.8" has incorrect peer dependency "gatsby-plugin-sharp@^2.6.8".
warning "gatsby-source-wordpress-experimental > @babel/plugin-proposal-class-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > @babel/plugin-proposal-private-methods@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby@0.2.36" has unmet peer dependency "@babel/core@^7.0.0".
warning "gatsby-source-wordpress-experimental > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/plugin-proposal-optional-chaining@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/plugin-transform-runtime@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env@7.10.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/helper-compilation-targets@7.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-json-strings@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-numeric-separator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-syntax-class-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-syntax-numeric-separator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-syntax-top-level-await@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-block-scoping@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-classes@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-computed-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-destructuring@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-for-of@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-function-name@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-member-expression-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-modules-amd@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-modules-umd@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-new-target@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-object-super@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-parameters@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-property-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-regenerator@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-reserved-words@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-spread@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-template-literals@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-unicode-escapes@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-display-name@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-jsx@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-jsx-development@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-jsx-self@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-jsx-source@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-pure-annotations@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.10.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "gatsby-source-wordpress-experimental > babel-preset-gatsby > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.10.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "gatsby-source-wordpress-experimental > gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.3" has incorrect peer dependency "react-refresh@^0.8.2".
warning "gatsby-source-wordpress-experimental > gatsby > gatsby-admin > gatsby-interface@0.0.167" has incorrect peer dependency "react@16.8.1".
warning "gatsby-source-wordpress-experimental > gatsby > gatsby-admin > gatsby-interface@0.0.167" has incorrect peer dependency "react-dom@16.8.1".
warning "gatsby-source-wordpress-experimental > gatsby > gatsby-admin > gatsby-interface@0.0.167" has incorrect peer dependency "yup@^0.27.0".

<--- Last few GCs --->

[19360:0x39a0b00]   235529 ms: Mark-sweep 2037.5 (2056.6) -> 2035.8 (2058.3) MB, 1322.9 / 0.0 ms  (average mu = 0.094, current mu = 0.008) allocation failure scavenge might not succeed
[19360:0x39a0b00]   237130 ms: Mark-sweep 2043.9 (2062.8) -> 2039.0 (2070.3) MB, 1586.6 / 0.0 ms  (average mu = 0.043, current mu = 0.009) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0827ec7c08d1 <JSObject>
    0: builtin exit frame: concat(this=0x37217e4eb751 <JSArray[9]>,0x097205cd13b9 <String[#9]: react-dom>,0x37217e4eb751 <JSArray[9]>)

    1: getNewParts [0x2475f91f9c9] [/usr/share/yarn/lib/cli.js:~94371] [pc=0x571c133567e](this=0x399708cddc51 <PackageHoister map = 0x2988b9fb5d19>,0x37217e4e9959 <String[337]: gatsby-source-wordpress-experimental#gatsby#gatsby-plugin-page-creator#gatsby#gatsby-...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa09830 node::Abort() [node]
 2: 0xa09c55 node::OnFatalError(char const*, char const*) [node]
 3: 0xb7d71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb7da99 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd2a1f5  [node]
 6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd37105 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd37fb5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd3aa6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd012a2 v8::internal::Factory::AllocateRawWithAllocationSite(v8::internal::Handle<v8::internal::Map>, v8::internal::AllocationType, v8::internal::Handle<v8::internal::AllocationSite>) [node]
11: 0xd0cab4 v8::internal::Factory::NewJSArrayWithUnverifiedElements(v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, int, v8::internal::AllocationType) [node]
12: 0xd0cef9 v8::internal::Factory::NewJSArray(v8::internal::ElementsKind, int, int, v8::internal::ArrayStorageAllocationMode, v8::internal::AllocationType) [node]
13: 0xbf4b05  [node]
14: 0xbf51d8 v8::internal::Builtin_ArrayConcat(int, unsigned long*, v8::internal::Isolate*) [node]
15: 0x13c5c79  [node]
Aborted (core dumped)
```

**Comment by TylerBarnes** [comment] 2020-06-09 18:30
Interesting 🤔 thank you for the report!
A couple other people reported this as well but I wasn't able to reproduce on macOS / in my setup. Could you run `gatsby info` in the directory of your Gatsby site where you have this problem?
Thanks for trying out earlier versions to see when the problem started. I'm wondering if this is related to moving this project to it's own repo. There might have been an oversight in how it was publishing as part of the monorepo before vs being in it's own repo. 
Thanks again!

**Comment by pepsighan** [comment] 2020-06-10 01:23
```

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Languages:
    Python: 3.8.2 - /home/pepsighan/.pyenv/shims/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3

```

**Comment by tinder-kyleboss** [comment] 2020-06-19 18:53
I am able to reproduce as well:

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 74.0
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.21.16 => 2.21.16
    gatsby-image: ^2.2.32 => 2.4.3
    gatsby-link: ^2.4.1 => 2.4.2
    gatsby-plugin-catch-links: ^2.0.0 => 2.3.1
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-feed: ^2.0.0 => 2.5.1
    gatsby-plugin-gdpr-cookies: 1.0.7 => 1.0.7
    gatsby-plugin-lodash: ^3.0.1 => 3.3.1
    gatsby-plugin-manifest: ^2.3.3 => 2.4.3
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.1
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.0.0 => 2.3.1
    gatsby-plugin-sharp: 2.5.4 => 2.5.4
    gatsby-plugin-sitemap: 2.0.1 => 2.0.1
    gatsby-plugin-styled-components: ^3.0.0 => 3.3.1
    gatsby-plugin-twitter: ^2.0.0 => 2.3.1
    gatsby-react-router-scroll: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^2.1.8 => 2.3.3
    gatsby-source-wordpress: ^3.2.2 => 3.3.3
    gatsby-transformer-sharp: 2.4.4 => 2.4.4

**Comment by TylerBarnes** [comment] 2020-06-23 01:20
@pepsighan @tinder-kyleboss I believe I've identified the cause of this (though I still haven't been able to reproduce. Can you try `gatsby-source-wordpress-experimental@0.7.10` and let me know if it works for you?

Thanks!

**Comment by pepsighan** [comment] 2020-06-23 01:44
Woohoo! It worked. Thanks a lot. :+1:

**Comment by TylerBarnes** [comment] 2020-06-23 01:55
Yay :D so happy to hear that! Thanks for opening this issue and for your patience @pepsighan !

**Closed by TylerBarnes** 2020-06-23 01:55 UTC
Labels: bug, needs reproduction

**Comment by tinder-kyleboss** [comment] 2020-06-23 16:01
Thanks @TylerBarnes !! I can confirm this worked on my end as well :)

**Comment by TylerBarnes** [comment] 2020-06-23 16:25
Woo! So happy about that :D let me know if you run into any other problems. There's a fix coming soon for the other issue you were having @tinder-kyleboss !
