### ISSUE TITLE
Issue when I add over 48 Custom post types  - Request failed with status code 500

### ISSUE THREAD

**Issue by MilanPoznan** [gatsbyjs/gatsby-source-wordpress-experimental#201] opened 2020-10-07 14:31 UTC
Dear all, 

I am using gatsby-source-wordpress-experimental and now I am getting this error : 

error  gatsby-source-wordpress  Request failed with status code 500
4:24:51 PM: Error occured while fetching nodes of the "Discount" type.
4:24:51 PM: GraphQL request to https://student-wp.jldevelopment.is/graphql failed.
4:24:51 PM: Please ensure the following statements are true
4:24:51 PM:   - your WordPress URL is correct in gatsby-config.js
4:24:51 PM:   - your server is responding to requests
4:24:51 PM:   - WPGraphQL and WPGatsby are installed in your WordPress backend

Error message
4:24:51 PM:   Command failed with exit code 1: GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
4:24:51 PM: ​
4:24:51 PM:   Error location
4:24:51 PM:   In Build command from Netlify app:
4:24:51 PM:   GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
4:24:51 PM: ​
4:24:51 PM:   Resolved config
4:24:51 PM:   build:
4:24:51 PM:     command: GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
4:24:51 PM:     commandOrigin: ui
4:24:51 PM:     environment:
4:24:51 PM:       - GATSBY_WP_URL
4:24:51 PM:     publish: /opt/build/repo/public

So can anyone help and tell me what to do?

**Comment by MilanPoznan** [comment] 2020-10-07 14:44
So when I exclude this custom post type from grapqhl everything works, but with it, but when I enable it I get this error.

**Comment by TylerBarnes** [comment] 2020-10-09 00:32
Hi @MilanPoznan, the reason is that the plugin will by default try to fetch up to 200 post types concurrently. If you lower the `GATSBY_CONCURRENT_DOWNLOAD` env var to 40 your build should keep working. Follow this guide to set that env var https://www.gatsbyjs.com/docs/environment-variables/

Closing this as a dupe of #85

**Closed by TylerBarnes** 2020-10-09 00:32 UTC
