### ISSUE TITLE
Inline Image Processing: Allow for Shared Options for Sharp Fluid Query

### ISSUE THREAD

**Issue by 0aveRyan** [gatsbyjs/gatsby-source-wordpress-experimental#100] opened 2020-07-29 18:54 UTC
https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/#shared-options

It'd be great to be able to pass a single object to configure sharp to the `html` pluginOptions  with `toFormat` and `traceSVG` in particular.

**Comment by TylerBarnes** [comment] 2020-08-07 00:24
I agree 100%, we'll definitely be adding this as an option after the first stable release. Thanks for suggesting this!

**Comment by TylerBarnes** [comment] 2020-11-19 04:43
Closing this as a duplicate of #71 

Thanks again for the awesome suggestion :D

**Closed by TylerBarnes** 2020-11-19 04:43 UTC
Labels: enhancement, good first issue, todo after v4 release
